### ISSUE TITLE
Programmatic API endpoints getting deprecated: Will this still work post December 2016?

### ISSUE THREAD

**Issue by yogiccode** [GanadiniAkshay/LUISTrainer#1]

**Comment by GanadiniAkshay** [comment]
Yes that is a issue. In the current form it won't. I will try to fix it. Also it's not programmatic endpoint being shut down. Its just that you won't have free keys and need an azure subscription.

**Comment by GanadiniAkshay** [comment]
Looks like this is not an issue and it still works so closing this.
